name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  # Build and create GitHub release with GoReleaser
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish to NPM after GitHub release is created
  publish-npm:
    needs: goreleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Update package version from release tag
        run: |
          # Extract version from release tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Updating package.json version to $VERSION"

          # Update package.json version
          npm version $VERSION --no-git-tag-version

          # Show the updated package.json
          cat package.json | grep '"version"'

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Verify publication
        run: |
          echo "Verifying package was published..."
          npm view @jjojo/herald version

      - name: Create summary
        run: |
          echo "## 🚀 Release Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### GitHub Release" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Release:** https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### NPM Package" >> $GITHUB_STEP_SUMMARY
          echo "- **Package:** \`@jjojo/herald\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Version:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry:** https://www.npmjs.com/package/@jjojo/herald" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Installation" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# Direct usage" >> $GITHUB_STEP_SUMMARY
          echo "npx @jjojo/herald --help" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Global installation" >> $GITHUB_STEP_SUMMARY
          echo "npm install -g @jjojo/herald" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Local installation" >> $GITHUB_STEP_SUMMARY
          echo "npm install @jjojo/herald" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
